---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jabbarst/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.jsx $DEPLOYPATH
    - /bin/cp app.jsx $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
